title: Adam Sami # your name (or website title) here
logo: "/images/headshot.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Data analyst specializing in risk management and fraud prevention within the fintech sector. Extensive experience in designing and implementing robust risk controls and fraud prevention strategies with particular emphasis on building and refining rule-based systems for transaction monitoring, fraud detection, and compliance.
 <br><br>
 Experienced and highly proficient with Python, SQL, Excel and Tableau.
 <br><br>
  <a href="https://www.linkedin.com/in/adamsami/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
